### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by Greger312** [pollev/python-websocket-proxy#2]
Is this project dead? I just get issues trying to run it:

Exception occurred during processing of request from ('127.0.0.1', 52432)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\\@@@@@\websocket_http_proxy.py", line 81, in __init__
    BaseHTTPRequestHandler.__init__(self, *args, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 755, in __init__
    self.handle()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
  File "C:\Users\\@@@@@\websocket_http_proxy.py", line 85, in do_CONNECT
    self.connect_intercept()
  File "C:\Users\\@@@@@\websocket_http_proxy.py", line 109, in connect_intercept
    self.connection = ssl_settings.wrap_socket(self.connection, server_side=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1108, in _create
    self.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1006)

Set up the certs just like setup_https_intercept.sh said, works without the certs but cant seem to intercept the websocket then.

**Comment by pollev** [comment]
Nope should be working. Do note that this is not some battle tested library. It's just my own implementation because I had a need for it. If you want a more mature framework, consider checking out https://github.com/mitmproxy/mitmproxy.

Other than that, I can't say for sure why you are getting this error. If you generated the certificates properly and imported the root CA into your browser as a trusted CA it should work fine.
